### ISSUE TITLE
What is the main difference between yours and that?

### ISSUE THREAD

**Issue by XinyueZ** [jiawen-zhu/HQTrack#16]
Hey dude,

     Compare to https://github.com/gaomingqi/Track-Anything

I mean except HQ Sam and your tracker backbone, in previous one they were using Xmem for tacking.

Also those https://github.com/z-x-yang/Segment-and-Track-Anything

https://github.com/qiaoyu1002/Inpaint-Anything

Thanks

**Comment by jiawen-zhu** [comment]
Hi~ Thanks for your attention.
The methods you mentioned are excellent SAM-based works.
Compared with them, HQTrack is the first tracking-anything method used in practice (VOTS2023), and promising performance is obtained. Except adopting HQ-SAM and more powerful backbone, HQTrack: 
1. increases feature scales for mask propagation, enabling more accurate mask prediction and tiny-object-friendly.
2. selects the mask from VMOS and SAM refiner as the final result, instead of fully provided by SAM.
By the way, HQTrack is relatively simpler and newbie friendly.
